version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/database/Dockerfile
    image: database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - lib-network
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql

  app:
    build:
      context: .
      dockerfile: docker/application/Dockerfile
    image: app
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres
    networks:
      - lib-network
    restart: always
    volumes:
      - ./src:/app/dev

volumes:
  postgres_data: # Declare the volume for database files
  postgres_logs: # Declare the volume for logs

networks:
  lib-network:
    driver: bridge
